[2025-01-18T21:22:31.055+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-18T21:22:31.064+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2025-01-18T21:22:31.068+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2025-01-18T21:22:31.069+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-18T21:22:31.138+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2023-05-10 00:00:00+00:00
[2025-01-18T21:22:31.142+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=301) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-18T21:22:31.143+0000] {standard_task_runner.py:72} INFO - Started process 314 to run task
[2025-01-18T21:22:31.144+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2023-05-10T00:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpyho2aulm']
[2025-01-18T21:22:31.145+0000] {standard_task_runner.py:105} INFO - Job 111: Subtask extract
[2025-01-18T21:22:31.180+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [running]> on host e9a1739d3128
[2025-01-18T21:22:31.241+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T00:00:00+00:00'
[2025-01-18T21:22:31.243+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-18T21:22:31.259+0000] {logging_mixin.py:190} INFO - 2023-05
[2025-01-18T21:22:31.433+0000] {logging_mixin.py:190} INFO - Arquivos encontrados no diret√≥rio https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-05:
[2025-01-18T21:22:31.434+0000] {logging_mixin.py:190} INFO - ['Cnaes.zip', 'Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip', 'Estabelecimentos0.zip', 'Estabelecimentos1.zip', 'Estabelecimentos2.zip', 'Estabelecimentos3.zip', 'Estabelecimentos4.zip', 'Estabelecimentos5.zip', 'Estabelecimentos6.zip', 'Estabelecimentos7.zip', 'Estabelecimentos8.zip', 'Estabelecimentos9.zip', 'Motivos.zip', 'Municipios.zip', 'Naturezas.zip', 'Paises.zip', 'Qualificacoes.zip', 'Simples.zip', 'Socios0.zip', 'Socios1.zip', 'Socios2.zip', 'Socios3.zip', 'Socios4.zip', 'Socios5.zip', 'Socios6.zip', 'Socios7.zip', 'Socios8.zip', 'Socios9.zip']
[2025-01-18T21:22:31.434+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-18T21:22:31.440+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-18T21:22:31.441+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2023-05-10T00:00:00+00:00, execution_date=20230510T000000, start_date=20250118T212231, end_date=20250118T212231
[2025-01-18T21:22:31.478+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-18T21:22:31.488+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-18T21:22:31.822+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T20:06:51.948+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T20:06:51.960+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2025-01-19T20:06:51.966+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2025-01-19T20:06:51.967+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T20:06:52.002+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2023-05-10 00:00:00+00:00
[2025-01-19T20:06:52.006+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T20:06:52.009+0000] {standard_task_runner.py:72} INFO - Started process 198 to run task
[2025-01-19T20:06:52.008+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2023-05-10T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpnj0v57y6']
[2025-01-19T20:06:52.009+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask extract
[2025-01-19T20:06:52.044+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [running]> on host 659dab735c6e
[2025-01-19T20:06:52.101+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T00:00:00+00:00'
[2025-01-19T20:06:52.102+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T20:06:52.125+0000] {logging_mixin.py:190} INFO - 2023-05
[2025-01-19T20:06:52.444+0000] {logging_mixin.py:190} INFO - -----------------
[2025-01-19T20:06:52.444+0000] {logging_mixin.py:190} INFO - ['Cnaes.zip']
[2025-01-19T20:06:52.445+0000] {logging_mixin.py:190} INFO - ['Cnaes']
[2025-01-19T20:06:52.607+0000] {logging_mixin.py:190} INFO - Arquivo salvo em: G:/Airlfow/volumes/dados_abertos_cnpj/2023-05/Cnaes/Cnaes.zip
[2025-01-19T20:06:53.128+0000] {logging_mixin.py:190} INFO - None
[2025-01-19T20:06:53.129+0000] {logging_mixin.py:190} INFO - ['Cnaes.zip']
[2025-01-19T20:06:53.130+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-19T20:06:53.138+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T20:06:53.138+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2023-05-10T00:00:00+00:00, execution_date=20230510T000000, start_date=20250119T200651, end_date=20250119T200653
[2025-01-19T20:06:53.185+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-19T20:06:53.206+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-19T20:06:53.208+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T22:19:33.766+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T22:19:33.776+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2025-01-19T22:19:33.781+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2025-01-19T22:19:33.782+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T22:19:33.792+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2023-05-10 00:00:00+00:00
[2025-01-19T22:19:33.796+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=497) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T22:19:33.797+0000] {standard_task_runner.py:72} INFO - Started process 504 to run task
[2025-01-19T22:19:33.797+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2023-05-10T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmprlvt54l6']
[2025-01-19T22:19:33.799+0000] {standard_task_runner.py:105} INFO - Job 155: Subtask extract
[2025-01-19T22:19:33.831+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [running]> on host 659dab735c6e
[2025-01-19T22:19:33.882+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T00:00:00+00:00'
[2025-01-19T22:19:33.883+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T22:19:33.972+0000] {logging_mixin.py:190} INFO - 2023-05
[2025-01-19T22:19:34.152+0000] {logging_mixin.py:190} INFO - -----------------
[2025-01-19T22:19:34.153+0000] {logging_mixin.py:190} INFO - ['Cnaes.zip', 'Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip', 'Estabelecimentos0.zip', 'Estabelecimentos1.zip', 'Estabelecimentos2.zip', 'Estabelecimentos3.zip', 'Estabelecimentos4.zip', 'Estabelecimentos5.zip', 'Estabelecimentos6.zip', 'Estabelecimentos7.zip', 'Estabelecimentos8.zip', 'Estabelecimentos9.zip', 'Motivos.zip', 'Municipios.zip', 'Naturezas.zip', 'Paises.zip', 'Qualificacoes.zip', 'Simples.zip', 'Socios0.zip', 'Socios1.zip', 'Socios2.zip', 'Socios3.zip', 'Socios4.zip', 'Socios5.zip', 'Socios6.zip', 'Socios7.zip', 'Socios8.zip', 'Socios9.zip']
[2025-01-19T22:19:34.153+0000] {logging_mixin.py:190} INFO - ['Cnaes', 'Empresas', 'Estabelecimentos', 'Motivos', 'Municipios', 'Naturezas', 'Paises', 'Qualificacoes', 'Simples', 'Socios']
[2025-01-19T22:19:34.153+0000] {logging_mixin.py:190} INFO - Iniciando o download de: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-05/Cnaes.zip
[2025-01-19T22:19:34.314+0000] {logging_mixin.py:190} INFO - Arquivo salvo em: G:/Airflow/volumes/dados_abertos_cnpj/2023-05/Cnaes/Cnaes.zip
[2025-01-19T22:19:34.315+0000] {logging_mixin.py:190} INFO - Iniciando o download de: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-05/Empresas0.zip
[2025-01-23T01:22:35.867+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-23T01:22:35.874+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-01-23T01:22:35.880+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-01-23T01:22:35.897+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2025-01-24T19:01:29.475+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T19:01:29.484+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2025-01-24T19:01:29.489+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [queued]>
[2025-01-24T19:01:29.490+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T19:01:29.498+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2023-05-10 00:00:00+00:00
[2025-01-24T19:01:29.503+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1282) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T19:01:29.504+0000] {standard_task_runner.py:72} INFO - Started process 1288 to run task
[2025-01-24T19:01:29.504+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2023-05-10T00:00:00+00:00', '--job-id', '573', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmp3qeph0t9']
[2025-01-24T19:01:29.505+0000] {standard_task_runner.py:105} INFO - Job 573: Subtask extract
[2025-01-24T19:01:29.530+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2023-05-10T00:00:00+00:00 [running]> on host ee70781c29c7
[2025-01-24T19:01:29.579+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T00:00:00+00:00'
[2025-01-24T19:01:29.579+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T19:01:29.590+0000] {logging_mixin.py:190} INFO - Data formatada: 2023-05
[2025-01-24T19:01:29.847+0000] {logging_mixin.py:190} INFO - Arquivos encontrados: ['Cnaes.zip', 'Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip', 'Estabelecimentos0.zip', 'Estabelecimentos1.zip', 'Estabelecimentos2.zip', 'Estabelecimentos3.zip', 'Estabelecimentos4.zip', 'Estabelecimentos5.zip', 'Estabelecimentos6.zip', 'Estabelecimentos7.zip', 'Estabelecimentos8.zip', 'Estabelecimentos9.zip', 'Motivos.zip', 'Municipios.zip', 'Naturezas.zip', 'Paises.zip', 'Qualificacoes.zip', 'Simples.zip', 'Socios0.zip', 'Socios1.zip', 'Socios2.zip', 'Socios3.zip', 'Socios4.zip', 'Socios5.zip', 'Socios6.zip', 'Socios7.zip', 'Socios8.zip', 'Socios9.zip']
[2025-01-24T19:01:29.847+0000] {logging_mixin.py:190} INFO - Baixando o arquivo: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-05/Cnaes.zip
[2025-01-24T19:01:30.000+0000] {logging_mixin.py:190} INFO - Download conclu√≠do: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2023-05/Cnaes.zip
[2025-01-24T19:01:30.003+0000] {logging_mixin.py:190} INFO - Arquivos descompactados: ['/tmp/1d63a1057d5542e6882c9313ae735b7c_extracted/F.K03200$Z.D30513.CNAECSV']
[2025-01-24T19:01:30.008+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 134, in extract
    upload_to_bucket(
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 100, in upload_to_bucket
    client.put_object(
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1996, in put_object
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1942, in put_object
    return self._put_object(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1781, in _put_object
    response = self._execute(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 438, in _execute
    region = self._get_region(bucket_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 495, in _get_region
    response = self._url_open(
               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 424, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /raw, request_id: 181DB622610187C4, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: raw
[2025-01-24T19:01:30.018+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2023-05-10T00:00:00+00:00, execution_date=20230510T000000, start_date=20250124T190129, end_date=20250124T190130
[2025-01-24T19:01:30.036+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T19:01:30.037+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 573 for task extract (S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /raw, request_id: 181DB622610187C4, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: raw; 1288)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 134, in extract
    upload_to_bucket(
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 100, in upload_to_bucket
    client.put_object(
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1996, in put_object
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1942, in put_object
    return self._put_object(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1781, in _put_object
    response = self._execute(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 438, in _execute
    region = self._get_region(bucket_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 495, in _get_region
    response = self._url_open(
               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 424, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /raw, request_id: 181DB622610187C4, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: raw
[2025-01-24T19:01:30.079+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T19:01:30.084+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
