[2025-01-18T21:22:32.097+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-18T21:22:32.106+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [queued]>
[2025-01-18T21:22:32.110+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [queued]>
[2025-01-18T21:22:32.110+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-18T21:22:32.141+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-02-10 00:00:00+00:00
[2025-01-18T21:22:32.144+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=326) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-18T21:22:32.145+0000] {standard_task_runner.py:72} INFO - Started process 335 to run task
[2025-01-18T21:22:32.146+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2024-02-10T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpvri74kyb']
[2025-01-18T21:22:32.147+0000] {standard_task_runner.py:105} INFO - Job 120: Subtask extract
[2025-01-18T21:22:32.172+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [running]> on host e9a1739d3128
[2025-01-18T21:22:32.223+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-10T00:00:00+00:00'
[2025-01-18T21:22:32.224+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-18T21:22:32.236+0000] {logging_mixin.py:190} INFO - 2024-02
[2025-01-18T21:22:32.416+0000] {logging_mixin.py:190} INFO - Arquivos encontrados no diret√≥rio https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2024-02:
[2025-01-18T21:22:32.417+0000] {logging_mixin.py:190} INFO - ['Cnaes.zip', 'Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip', 'Estabelecimentos0.zip', 'Estabelecimentos1.zip', 'Estabelecimentos2.zip', 'Estabelecimentos3.zip', 'Estabelecimentos4.zip', 'Estabelecimentos5.zip', 'Estabelecimentos6.zip', 'Estabelecimentos7.zip', 'Estabelecimentos8.zip', 'Estabelecimentos9.zip', 'Motivos.zip', 'Municipios.zip', 'Naturezas.zip', 'Paises.zip', 'Qualificacoes.zip', 'Simples.zip', 'Socios0.zip', 'Socios1.zip', 'Socios2.zip', 'Socios3.zip', 'Socios4.zip', 'Socios5.zip', 'Socios6.zip', 'Socios7.zip', 'Socios8.zip', 'Socios9.zip']
[2025-01-18T21:22:32.417+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-18T21:22:32.423+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-18T21:22:32.423+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2024-02-10T00:00:00+00:00, execution_date=20240210T000000, start_date=20250118T212232, end_date=20250118T212232
[2025-01-18T21:22:32.439+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-18T21:22:32.447+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-18T21:22:32.449+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T20:06:53.191+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T20:06:53.204+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [queued]>
[2025-01-19T20:06:53.211+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [queued]>
[2025-01-19T20:06:53.211+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T20:06:53.223+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-02-10 00:00:00+00:00
[2025-01-19T20:06:53.226+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=211) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T20:06:53.228+0000] {standard_task_runner.py:72} INFO - Started process 226 to run task
[2025-01-19T20:06:53.228+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2024-02-10T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmptzxys7hl']
[2025-01-19T20:06:53.230+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask extract
[2025-01-19T20:06:53.267+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [running]> on host 659dab735c6e
[2025-01-19T20:06:53.323+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-10T00:00:00+00:00'
[2025-01-19T20:06:53.323+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T20:06:53.336+0000] {logging_mixin.py:190} INFO - 2024-02
[2025-01-19T20:06:53.508+0000] {logging_mixin.py:190} INFO - -----------------
[2025-01-19T20:06:53.509+0000] {logging_mixin.py:190} INFO - ['Cnaes.zip']
[2025-01-19T20:06:53.509+0000] {logging_mixin.py:190} INFO - ['Cnaes']
[2025-01-19T20:06:53.669+0000] {logging_mixin.py:190} INFO - Arquivo salvo em: G:/Airlfow/volumes/dados_abertos_cnpj/2024-02/Cnaes/Cnaes.zip
[2025-01-19T20:06:53.669+0000] {logging_mixin.py:190} INFO - None
[2025-01-19T20:06:53.670+0000] {logging_mixin.py:190} INFO - ['Cnaes.zip']
[2025-01-19T20:06:53.670+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-19T20:06:53.676+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T20:06:53.676+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2024-02-10T00:00:00+00:00, execution_date=20240210T000000, start_date=20250119T200653, end_date=20250119T200653
[2025-01-19T20:06:53.722+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-19T20:06:53.736+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-19T20:06:53.738+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T22:19:34.656+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T22:19:34.670+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [queued]>
[2025-01-19T22:19:34.676+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [queued]>
[2025-01-19T22:19:34.676+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T22:19:34.685+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-02-10 00:00:00+00:00
[2025-01-19T22:19:34.689+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=520) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T22:19:34.690+0000] {standard_task_runner.py:72} INFO - Started process 529 to run task
[2025-01-19T22:19:34.690+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2024-02-10T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmpihjl7ko9']
[2025-01-19T22:19:34.692+0000] {standard_task_runner.py:105} INFO - Job 164: Subtask extract
[2025-01-19T22:19:34.720+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [running]> on host 659dab735c6e
[2025-01-19T22:19:34.772+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-10T00:00:00+00:00'
[2025-01-19T22:19:34.773+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T22:19:34.786+0000] {logging_mixin.py:190} INFO - 2024-02
[2025-01-19T22:19:34.957+0000] {logging_mixin.py:190} INFO - -----------------
[2025-01-19T22:19:34.958+0000] {logging_mixin.py:190} INFO - ['Cnaes.zip', 'Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip', 'Estabelecimentos0.zip', 'Estabelecimentos1.zip', 'Estabelecimentos2.zip', 'Estabelecimentos3.zip', 'Estabelecimentos4.zip', 'Estabelecimentos5.zip', 'Estabelecimentos6.zip', 'Estabelecimentos7.zip', 'Estabelecimentos8.zip', 'Estabelecimentos9.zip', 'Motivos.zip', 'Municipios.zip', 'Naturezas.zip', 'Paises.zip', 'Qualificacoes.zip', 'Simples.zip', 'Socios0.zip', 'Socios1.zip', 'Socios2.zip', 'Socios3.zip', 'Socios4.zip', 'Socios5.zip', 'Socios6.zip', 'Socios7.zip', 'Socios8.zip', 'Socios9.zip']
[2025-01-19T22:19:34.958+0000] {logging_mixin.py:190} INFO - ['Cnaes', 'Empresas', 'Estabelecimentos', 'Motivos', 'Municipios', 'Naturezas', 'Paises', 'Qualificacoes', 'Simples', 'Socios']
[2025-01-19T22:19:34.958+0000] {logging_mixin.py:190} INFO - Iniciando o download de: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2024-02/Cnaes.zip
[2025-01-19T22:19:35.126+0000] {logging_mixin.py:190} INFO - Arquivo salvo em: G:/Airflow/volumes/dados_abertos_cnpj/2024-02/Cnaes/Cnaes.zip
[2025-01-19T22:19:35.127+0000] {logging_mixin.py:190} INFO - Iniciando o download de: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2024-02/Empresas0.zip
[2025-01-23T01:22:35.872+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-23T01:22:35.879+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-01-23T01:22:35.883+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-01-23T01:22:35.915+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2025-01-24T19:01:30.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T19:01:30.221+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [queued]>
[2025-01-24T19:01:30.226+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [queued]>
[2025-01-24T19:01:30.226+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T19:01:30.283+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-02-10 00:00:00+00:00
[2025-01-24T19:01:30.287+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1299) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T19:01:30.288+0000] {standard_task_runner.py:72} INFO - Started process 1313 to run task
[2025-01-24T19:01:30.288+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coleta_dados_abertos_cnpj', 'extract', 'scheduled__2024-02-10T00:00:00+00:00', '--job-id', '582', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados_abertos_cnpj/dag.py', '--cfg-path', '/tmp/tmproso7py0']
[2025-01-24T19:01:30.290+0000] {standard_task_runner.py:105} INFO - Job 582: Subtask extract
[2025-01-24T19:01:30.314+0000] {task_command.py:467} INFO - Running <TaskInstance: coleta_dados_abertos_cnpj.extract scheduled__2024-02-10T00:00:00+00:00 [running]> on host ee70781c29c7
[2025-01-24T19:01:30.363+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Corvaum' AIRFLOW_CTX_DAG_ID='coleta_dados_abertos_cnpj' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-10T00:00:00+00:00'
[2025-01-24T19:01:30.364+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T19:01:30.374+0000] {logging_mixin.py:190} INFO - Data formatada: 2024-02
[2025-01-24T19:01:30.547+0000] {logging_mixin.py:190} INFO - Arquivos encontrados: ['Cnaes.zip', 'Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip', 'Estabelecimentos0.zip', 'Estabelecimentos1.zip', 'Estabelecimentos2.zip', 'Estabelecimentos3.zip', 'Estabelecimentos4.zip', 'Estabelecimentos5.zip', 'Estabelecimentos6.zip', 'Estabelecimentos7.zip', 'Estabelecimentos8.zip', 'Estabelecimentos9.zip', 'Motivos.zip', 'Municipios.zip', 'Naturezas.zip', 'Paises.zip', 'Qualificacoes.zip', 'Simples.zip', 'Socios0.zip', 'Socios1.zip', 'Socios2.zip', 'Socios3.zip', 'Socios4.zip', 'Socios5.zip', 'Socios6.zip', 'Socios7.zip', 'Socios8.zip', 'Socios9.zip']
[2025-01-24T19:01:30.547+0000] {logging_mixin.py:190} INFO - Baixando o arquivo: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2024-02/Cnaes.zip
[2025-01-24T19:01:30.703+0000] {logging_mixin.py:190} INFO - Download conclu√≠do: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/2024-02/Cnaes.zip
[2025-01-24T19:01:30.705+0000] {logging_mixin.py:190} INFO - Arquivos descompactados: ['/tmp/85f40ca3cf1b4e278662de1c21b2c038_extracted/F.K03200$Z.D40210.CNAECSV']
[2025-01-24T19:01:30.710+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 134, in extract
    upload_to_bucket(
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 100, in upload_to_bucket
    client.put_object(
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1996, in put_object
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1942, in put_object
    return self._put_object(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1781, in _put_object
    response = self._execute(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 438, in _execute
    region = self._get_region(bucket_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 495, in _get_region
    response = self._url_open(
               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 424, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /raw, request_id: 181DB6228AD4F687, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: raw
[2025-01-24T19:01:30.722+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=coleta_dados_abertos_cnpj, task_id=extract, run_id=scheduled__2024-02-10T00:00:00+00:00, execution_date=20240210T000000, start_date=20250124T190130, end_date=20250124T190130
[2025-01-24T19:01:30.731+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T19:01:30.731+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 582 for task extract (S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /raw, request_id: 181DB6228AD4F687, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: raw; 1313)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 134, in extract
    upload_to_bucket(
  File "/opt/airflow/dags/coleta_dados_abertos_cnpj/jobs/extract.py", line 100, in upload_to_bucket
    client.put_object(
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1996, in put_object
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1942, in put_object
    return self._put_object(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 1781, in _put_object
    response = self._execute(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 438, in _execute
    region = self._get_region(bucket_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 495, in _get_region
    response = self._url_open(
               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 424, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NoSuchBucket, message: The specified bucket does not exist, resource: /raw, request_id: 181DB6228AD4F687, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: raw
[2025-01-24T19:01:30.742+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T19:01:30.755+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T19:01:30.757+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
